import cors from "@fastify/cors";
import fp from "fastify-plugin";
import type { FastifyInstance } from "fastify";

function parseOrigins(input: string | undefined): string[] | boolean {
  if (!input) return true;
  const origins = input
    .split(",")
    .map((o) => o.trim())
    .filter(Boolean);
  return origins.length > 0 ? origins : true;
}

// Wrapped with fastify-plugin so the CORS hook is registered on the parent
// Fastify instance rather than an encapsulated child context. Without this,
// responses generated by Fastify's built-in error handlers (e.g. body-parser
// 400s, 404s, validation errors) do NOT include the Access-Control-Allow-Origin
// header, which causes browsers to mask the real status code behind a
// "CORS Missing Allow Origin" error.
export const corsPlugin = fp(async function corsPlugin(app: FastifyInstance) {
  const allowedOrigins = parseOrigins(process.env.ALLOWED_ORIGINS);

  await app.register(cors, {
    origin: allowedOrigins,
    credentials: true,
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  });
});
